# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://sgaseretto.github.io/nopeeknn/"

git_url = "https://github.com/sgaseretto/nopeeknn/tree/master/"

def custom_doc_links(name): return None
